# Generated by Django 5.1.7 on 2025-04-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('html_file', models.FileField(upload_to='templates_to_be_edited/')),
                ('thumbnail', models.ImageField(upload_to='templates_thumbnails/')),
            ],
        ),
    ]
