# Generated by Django 5.1.7 on 2025-04-20 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Template_Editor_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='html_file',
        ),
        migrations.RemoveField(
            model_name='template',
            name='thumbnail',
        ),
        migrations.CreateModel(
            name='TemplatePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('html_file', models.FileField(upload_to='templates_parts/html/')),
                ('thumbnail', models.ImageField(upload_to='templates_parts/thumbnails/')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='Template_Editor_App.template')),
            ],
        ),
    ]
