# Generated by Django 5.1.7 on 2025-04-21 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Template_Editor_App', '0002_remove_template_html_file_remove_template_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='cover_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_as_cover_for', to='Template_Editor_App.templatepart'),
        ),
    ]
