# Generated by Django 5.1.7 on 2025-04-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Template_Editor_App', '0003_template_cover_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='html_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
