# Generated by Django 5.1.7 on 2025-04-26 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Template_Editor_App', '0004_template_html_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='html_file',
        ),
    ]
