# Generated by Django 5.1.7 on 2025-06-06 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Template_Editor_App', '0005_remove_template_html_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTemplateEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_parts', models.JSONField(default=dict)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_edits', to='Template_Editor_App.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_edits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
